#include "position.h"
#include "pieces.h"

static const Piece STARTING_POSITION[10][9] = 
{
    {BLACK_CHARIOT, BLACK_HORSE, BLACK_ELEPHANT, BLACK_ADVISOR, BLACK_GENERAL, BLACK_ADVISOR, BLACK_ELEPHANT, BLACK_HORSE, BLACK_CHARIOT},
    {EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY},
    {EMPTY,BLACK_CANNON,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,BLACK_CANNON,EMPTY},
    {BLACK_SOLDIER,EMPTY,BLACK_SOLDIER,EMPTY,BLACK_SOLDIER,EMPTY,BLACK_SOLDIER,EMPTY,BLACK_SOLDIER},
    {EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY},
    {EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY},
    {RED_SOLDIER,EMPTY,RED_SOLDIER,EMPTY,RED_SOLDIER,EMPTY,RED_SOLDIER,EMPTY,RED_SOLDIER},
    {EMPTY,RED_CANNON,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,RED_CANNON,EMPTY},
    {EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY,EMPTY},
    {RED_CHARIOT,RED_HORSE,RED_ELEPHANT,RED_ADVISOR,RED_GENERAL,RED_ADVISOR,RED_ELEPHANT,RED_HORSE,RED_CHARIOT}
};

Position::Position() {
    for (int row = 0; row < 10; row++) {
        for (int col = 0; col < 9; col++) {
            board[row][col] = STARTING_POSITION[row][col];
        }
    }

    sideToMove = RED;
}